ALTER TABLE country ADD CONSTRAINT UQ_NAME_COUNTRY UNIQUE (name);
ALTER TABLE band ADD CONSTRAINT UQ_NAME_BAND UNIQUE (name);
ALTER TABLE member ADD CONSTRAINT UQ_NAME_MEMBER UNIQUE (name);
ALTER TABLE tour ADD CONSTRAINT UQ_NAME_TOUR UNIQUE (name);
ALTER TABLE member_role ADD CONSTRAINT UQ_NAME_MEMBER_ROLE UNIQUE (name);