CREATE SEQUENCE band_sequence START 1 INCREMENT 1;
CREATE SEQUENCE country_sequence START 1 INCREMENT 1;
CREATE SEQUENCE hit_parade_sequence START 1 INCREMENT 1;
CREATE SEQUENCE member_sequence START 1 INCREMENT 1;
CREATE SEQUENCE member_role_sequence START 1 INCREMENT 1;
CREATE SEQUENCE song_sequence START 1 INCREMENT 1;
CREATE SEQUENCE tour_sequence START 1 INCREMENT 1;
CREATE SEQUENCE user_entity_sequence START 1 INCREMENT 1;

CREATE SEQUENCE hit_parade_position_sequence START 1 INCREMENT 1;








